apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebc-static
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0c2e90cf65da278ff

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: ""
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: ebs-static
  labels:
    purpose: ebs-static
spec:
  nodeselector: 
    topology.kubernetes.io/zone: us-east-1c
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: ebs-static
  volumes:
    - name: ebs-static
      persistentVolumeClaim:
        claimName: ebs-static

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-static
  ports:
    - name: nginx-svc-port
      protocol: TCP
      port: 80 #service port
      targetPort: 80  #container port
      nodePort: 30007
