apiVersion: v1
kind: Service
metadata:
  name: nginx
spec: 
  selector:
    project: expense
    module: backend
    environment: dev
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80         #service port
    targetPort: 80   #pod port   
