apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-reader
  namespace: expense

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: expense
  name: secret-reader 
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader
  namespace: expense
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-reader
subjects:
- namespace: expense
  kind: ServiceAccount
  name: secret-reader

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  serviceAccountName: secret-reader
  containers:      #docker run -d --name nginx nginx
  - name: nginx  
    image: nginx

